/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_spark_shuffle_rdma_SparkRdmaNativeInterface */

#ifndef _Included_org_apache_spark_shuffle_rdma_SparkRdmaNativeInterface
#define _Included_org_apache_spark_shuffle_rdma_SparkRdmaNativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_spark_shuffle_rdma_SparkRdmaNativeInterface
 * Method:    map
 * Signature: (Ljava/io/FileDescriptor;JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_spark_shuffle_rdma_SparkRdmaNativeInterface_map
  (JNIEnv *, jobject, jobject, jlong, jlong);

/*
 * Class:     org_apache_spark_shuffle_rdma_SparkRdmaNativeInterface
 * Method:    unmap
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_apache_spark_shuffle_rdma_SparkRdmaNativeInterface_unmap
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_apache_spark_shuffle_rdma_SparkRdmaNativeInterface
 * Method:    writeBlocks
 * Signature: (I[I[IJJII)V
 */
JNIEXPORT void JNICALL Java_org_apache_spark_shuffle_rdma_SparkRdmaNativeInterface_writeBlocks
  (JNIEnv *, jobject, jint, jintArray, jintArray, jlong, jlong, jint, jint);

/*
 * Class:     org_apache_spark_shuffle_rdma_SparkRdmaNativeInterface
 * Method:    unregisterShuffle
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_apache_spark_shuffle_rdma_SparkRdmaNativeInterface_unregisterShuffle
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
